---
ansible_host: 2.29.4.239
ansible_user: root
app_port: 80

env: staging
domain_name: movaro.staging.toolkit23.com

docker_image: ghcr.io/piotrtrybala/movaro:v0.0.1

db_name: staging
db_container_name: movaro-db-staging
app_container_name: movaro-web-staging
caddy_container_name: movaro-caddy-staging
app_host_port: 80

data_dir: /opt/movaro_staging
